### ISSUE TITLE
Make copycol script SPW-friendly

### ISSUE THREAD

**Issue by IanHeywood** [IanHeywood/oxkat#32]

**Comment by IanHeywood** [comment]
Fixed here.

https://github.com/IanHeywood/oxkat/commit/3455b1548d4d6e60b86cf20c7d25a1a052281c8a

**Comment by IanHeywood** [comment]
```
ianh@slurm-login:/scratch2/users/ianh/TEST_1934/LOGS$ more slurm_CPDAT9_4.log
WARNING: destination /scratch2/users/ianh/TEST_1934 already in mount list: destination is already in the mount
 point list
WARNING: destination /scratch2/users/ianh/TEST_1934 already in mount list: destination is already in the mount
 point list
Successful read/write open of default-locked table 1601142995_sdp_l0_1024ch_GX_339-4.ms: 25 columns, 1891 rows
Spectral windows: [0]
Processing rows: 0 to 1891 for SPW 0
Traceback (most recent call last):
  File "/scratch2/users/ianh/TEST_1934/tools/copy_MS_column.py", line 70, in <module>
    main()
  File "/scratch2/users/ianh/TEST_1934/tools/copy_MS_column.py", line 64, in main
    copycol(msname,fromcol,tocol,field,rowchunk)
  File "/scratch2/users/ianh/TEST_1934/tools/copy_MS_column.py", line 35, in copycol
    spw_tab.putcol(tocol,spw_tab.getcol(fromcol,start_row,nr),start_row,nr)
  File "/usr/local/lib/python3.6/dist-packages/casacore/tables/table.py", line 1032, in getcol
    return self._getcol(columnname, startrow, nrow, rowincr)
RuntimeError: IPosition::getFirst(n); n is too high
****ELAPSED 4 CPDAT9_4
```

**Comment by IanHeywood** [comment]
This was a script futher up the chain trying to use f-strings in the python 2.7 that the wsclean container comes with.
