### ISSUE TITLE
Secondary model error

### ISSUE THREAD

**Issue by Sinenhlanhla** [IanHeywood/oxkat#43]
I am trying to reduce a multiple target (1 pcal, 2 scals, 3 targets) observation, and I am getting the error below.
Traceback (most recent call last):

  File "/data/mjh/casa-pipeline-release-5.6.1-8.el6/lib/python2.7/init_welcome.py", line 33, in <module>

    execfile(__candidates[0])

  File "/data/precious/merghers/epoch4a/oxkat/1GC_05_casa_get_secondary_model.py", line 374, in <module>

    iflux = secondary_models[str(pcal_idx)]['fitFluxd']

KeyError: '0'

****ELAPSED 9085 CLMOD020

**Comment by IanHeywood** [comment]
Hi @Sinenhlanhla. Can you please post the full CASA log associated with this step (or if the data are somewhere I can access point me to it)?

Also `/data/mjh/`, is this a LOFAR ddf-pipeline container?

**Comment by Sinenhlanhla** [comment]
The calibration log does not have any errors, however, the gaintables are only applied to the pcal. The error only appears in the mstransform step because there is no 'corrected_data' column. I've attached both the logs. The data is in hippo '/scratch/month/meerkat/MERGHERS2021/cfp2020_4a.ms'

/data/mjh is Matt's folder, I use his oxkat installation.
[casa-20220120-162104.log](https://github.com/IanHeywood/oxkat/files/7913106/casa-20220120-162104.log)
[casa-20220120-134715.log](https://github.com/IanHeywood/oxkat/files/7913109/casa-20220120-134715.log)

**Comment by IanHeywood** [comment]
Is this an old or modified version? The equivalent script in the current master has a different name:

```
1GC_07_casa_get_secondary_model.py
```

**Comment by Sinenhlanhla** [comment]
It is an older version. The script's name is `1GC_05_casa_get_secondary_model.py`

**Comment by IanHeywood** [comment]
Can you please try the current master (or dev branch) version and see if the problem persists?

**Comment by Sinenhlanhla** [comment]
I will try and update you.

**Comment by IanHeywood** [comment]
Thanks. I seem to remember there was some issue with running singularity on hippo, if that's where it's being run. There's a switch in the config to disable singularity entirely now:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/config.py#L37

which assumes that all the required executables are available and in the path. If the CASA executable is in a special place then just adding the full path to it here will hopefully allow that:

https://github.com/IanHeywood/oxkat/blob/master/oxkat/generate_jobs.py#L317

but it's getting a bit hacky at this point.

The problem looks like either the `secondary_models` dictionary isn't being populated, or that the model for source 0 is not present in it. If the `GAINTABLES` folder contains either `secondary_models_interim` or `secondary_models_final` pickles, can you please post those?

**Comment by Sinenhlanhla** [comment]
`secondary_models_interim` and `secondary_models_final` are not in the folder. Field '0' is a polarisation calibrator 'J1130-1449'. It could be that the model is not present because it also had to be added in caracal.

**Comment by IanHeywood** [comment]
I don't think that'll be the cause, the log says 1934 is being used as a primary, and the point of this section is to derive an intrinsic model for all the secondaries. If J1130 is not tagged as a secondary then it won't be added to the temporary `*calibrators.ms`. The log suggests this is the case. Field 0 in this temp MS might not correspond to field 0 in your master MS.

**Comment by Sinenhlanhla** [comment]
Okay, noted.

In the updated version, when I set USE_SINGULARITY = False, I get the following error:
Traceback (most recent call last):
  File "setups/1GC.py", line 373, in <module>
    main()
  File "setups/1GC.py", line 36, in main
    INFRASTRUCTURE, CONTAINER_PATH = gen.set_infrastructure(sys.argv)
  File "/data/precious/merghers/epoch4a/oxkat/generate_jobs.py", line 73, in set_infrastructure
    print(col('Container path')+CONTAINER_PATH)
TypeError: can only concatenate str (not "NoneType") to str

I commented out the print statement, and it sorted it out. I thought I should let you know because it seems like some syntax error.

**Comment by IanHeywood** [comment]
Thanks, I think that's a genuine bug. A hippo run sets the container path to `None`.

https://github.com/IanHeywood/oxkat/blob/master/oxkat/generate_jobs.py#L71

**Comment by MziyandaAstro** [comment]
Hi Ian.

The problem is that fluxscale populates secondary_models with fieldIds "1" and "2" and not with "0" which the code looks for first.

**Comment by MziyandaAstro** [comment]
I made this small modification on "1GC_05_casa_get_secondary_model.py" 

pcal_names_copy = pcal_names[:]
pcal_names_copy.remove(bpcal_name)
for i in range(0,len(pcal_names_copy)):
     pcal = pcal_names_copy[i] # Using field names

and the error goes away.

**Comment by MziyandaAstro** [comment]
After fixing the previous error, this next one pops up. 

Traceback (most recent call last):
  File "/data/mjh/casa-pipeline-release-5.6.1-8.el6/lib/python2.7/init_welcome.py", line 33, in <module>
    execfile(__candidates[0])
  File "/data/mziyanda/sarao/MERGHERS/kat_4b/mkates_4b/matt_oxkat/oxkat/1GC_06_casa_refcal_using_secondary_model.py", line 317, in <module>
    iflux = secondary_models[mod_idx]['fitFluxd']
NameError: name 'mod_idx' is not defined

I fixed this by making mod_idx  global variable (mod_idx=' ' before reassigning it in the for loop)

**Comment by IanHeywood** [comment]
Thanks @MziyandaAstro, if these problems occur in the current master or dev branches then I'll look into it further. Is it possible for me to get access to this MS somehow? I think I have a hippo login.

**Comment by Sinenhlanhla** [comment]
@IanHeywood with the updated version, the 1GC.py step successfully executed without any error.

**Comment by IanHeywood** [comment]
Thanks all, I'm assuming this can be closed in that case, but please reopen it if the problem happens again with the current version.

**Comment by IanHeywood** [comment]
The bug with the None type container path should be fixed by the way:

https://github.com/IanHeywood/oxkat/commit/d7afc4b6f4b939f97a7a1e818470c468b8412e79

**Comment by Sinenhlanhla** [comment]
@IanHeywood the data is in `/scratch/month/meerkat/MERGHERS2021/cfp2020_4a.ms`

**Comment by MziyandaAstro** [comment]
@IanHeywood, please go digging. It turns out that the current master does have some issues. I think you'll get a better understanding of these issues once you run things yourself.

**Comment by IanHeywood** [comment]
I have copied the data out to process elsewhere, but straight away I can see one issue that might be causing problems. The data have been observed with 4 second dump times. In 2 sec mode there is a MeerKAT bug that causes single integration scans to be present in the MS, however they are mislabeled and will actually contain visibilities for the previous scan, but with the appropriate metadata (including UVW) for the labeled scan. So for example a target scan with a single integration might contain calibrator visibilities from a preceding calibrator scan, which will put a very brief 4 second transient point source at the phase centre. 

You can see the offending scans in the table below. I'm not sure what the issues you're seeing now are, but in any case I'd recommend flagging out the scans with 1 or 2 integrations prior to processing the data in case the 2 sec bug also applies to 4 sec data. If you're using the dev branch then you can just list the scans you'd like to keep from the beginning here:

https://github.com/IanHeywood/oxkat/blob/dev/oxkat/config.py#L171

```
26/01/2022 12:50:52  |       SCAN  SOURCE_ID  NAME                  LENGTH[s]         INTS        INTENT
26/01/2022 12:50:52  |       1     0          J1130-1449            244.0             61          None
26/01/2022 12:50:52  |       2     1          J1939-6342            236.0             59          CALIBRATE_BANDPASS,CALIBRATE_FLUX
26/01/2022 12:50:52  |       3     0          J1130-1449            236.0             59          None
26/01/2022 12:50:52  |       4     2          J2145-5645            604.0             151         TARGET
26/01/2022 12:50:52  |       5     3          J2214-3835            92.0              23          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       6     4          J2131-4019            708.0             177         TARGET
26/01/2022 12:50:52  |       7     1          J1939-6342            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       8     2          J2145-5645            604.0             151         TARGET
26/01/2022 12:50:52  |       9     5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       10    6          J2116-0226            604.0             151         TARGET
26/01/2022 12:50:52  |       11    1          J1939-6342            4.0               1           CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       12    1          J1939-6342            92.0              23          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       13    2          J2145-5645            604.0             151         TARGET
26/01/2022 12:50:52  |       14    5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       15    6          J2116-0226            604.0             151         TARGET
26/01/2022 12:50:52  |       16    3          J2214-3835            4.0               1           CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       17    3          J2214-3835            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       18    4          J2131-4019            704.0             176         TARGET
26/01/2022 12:50:52  |       19    5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       20    6          J2116-0226            604.0             151         TARGET
26/01/2022 12:50:52  |       21    1          J1939-6342            4.0               1           CALIBRATE_BANDPASS,CALIBRATE_FLUX
26/01/2022 12:50:52  |       22    1          J1939-6342            236.0             59          CALIBRATE_BANDPASS,CALIBRATE_FLUX
26/01/2022 12:50:52  |       23    2          J2145-5645            600.0             150         TARGET
26/01/2022 12:50:52  |       24    5          J2134-0153            4.0               1           CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       25    5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       26    6          J2116-0226            604.0             151         TARGET
26/01/2022 12:50:52  |       27    3          J2214-3835            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       28    4          J2131-4019            708.0             177         TARGET
26/01/2022 12:50:52  |       29    5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       30    6          J2116-0226            608.0             152         TARGET
26/01/2022 12:50:52  |       31    1          J1939-6342            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       32    2          J2145-5645            600.0             150         TARGET
26/01/2022 12:50:52  |       33    5          J2134-0153            4.0               1           CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       34    5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       35    6          J2116-0226            600.0             150         TARGET
26/01/2022 12:50:52  |       36    1          J1939-6342            8.0               2           CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       37    1          J1939-6342            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       38    2          J2145-5645            604.0             151         TARGET
26/01/2022 12:50:52  |       39    5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       40    6          J2116-0226            608.0             152         TARGET
26/01/2022 12:50:52  |       41    3          J2214-3835            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       42    4          J2131-4019            704.0             176         TARGET
26/01/2022 12:50:52  |       43    5          J2134-0153            96.0              24          CALIBRATE_PHASE,CALIBRATE_AMPLI
26/01/2022 12:50:52  |       44    6          J2116-0226            604.0             151         TARGET
26/01/2022 12:50:52  |       45    1          J1939-6342            4.0               1           CALIBRATE_BANDPASS,CALIBRATE_FLUX
26/01/2022 12:50:52  |       46    1          J1939-6342            236.0             59          CALIBRATE_BANDPASS,CALIBRATE_FLUX
```

**Comment by IanHeywood** [comment]
Here is the list of 'good' scans:

```
1,2,3,4,5,6,7,8,9,10,12,13,14,15,17,18,19,20,22,23,25,26,27,28,29,30,31,32,34,35,37,38,39,40,41,42,43,44,46
```

**Comment by IanHeywood** [comment]
OK I suspect this is the problem:

```
26/01/2022 15:15:54  |       2     1          J1939-6342            232.0             29          CALIBRATE_BANDPASS,CALIBRATE_FLUX
26/01/2022 15:15:54  |       7     1          J1939-6342            94.0              11          CALIBRATE_PHASE,CALIBRATE_AMPLI
```

This field has mixed intents, being sometimes used the primary and sometimes as the secondary. The `fluxscale` task will at some point be run where the reference and transfer fields are the same, and will return nothing. However oxkat will be expecting a model for this field which it believes to be a secondary, and that's what's throwing the key error.

I think this should be handled gracefully but haven't thought about how to fix it yet. In the mean time a quick and dirty fix is probably to exclude the scans where J1939-6342 is tagged as a secondary, and to rely on the other calibrators and self-cal. I'm trying this now using the following scan selection:

```
1,2,3,4,5,6,8,9,10,13,14,15,17,18,19,20,22,23,25,26,27,28,29,30,32,34,35,38,39,40,41,42,43,44,46
```

**Comment by IanHeywood** [comment]
With the above scan selection fix this block ran all the way to the end of the 3GC stage without any issues, so I'm sure that having two different intents for the same source was the issue.
