### ISSUE TITLE
Tricolour data type error

### ISSUE THREAD

**Issue by Sinenhlanhla** [IanHeywood/oxkat#44]
I am getting this data type error, which results in poor 'datablind' images because the data is not flagged.

/data/mjh/anaconda3/lib/python3.7/site-packages/tricolour-0.1.7-py3.7.egg/tricolour/packing.py:346: PerformanceWarning: Increasing number of chunks by factor of 35
  dtype=np.bool)
/data/mjh/anaconda3/lib/python3.7/site-packages/tricolour-0.1.7-py3.7.egg/tricolour/packing.py:354: PerformanceWarning: Increasing number of chunks by factor of 35
  dtype=data.dtype)
/data/mjh/anaconda3/lib/python3.7/site-packages/tricolour-0.1.7-py3.7.egg/tricolour/packing.py:361: PerformanceWarning: Increasing number of chunks by factor of 35
  dtype=flags.dtype)
/data/mjh/anaconda3/lib/python3.7/site-packages/tricolour-0.1.7-py3.7.egg/tricolour/packing.py:425: PerformanceWarning: Increasing number of chunks by factor of 35
  dtype=flag_windows.dtype)
^M[#########                               ] | 24% Completed |  5min  0.1s
Traceback (most recent call last):
  File "/data/mjh/anaconda3/bin/tricolour", line 11, in <module>
    load_entry_point('tricolour==0.1.7', 'console_scripts', 'tricolour')()
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/tricolour-0.1.7-py3.7.egg/tricolour/apps/tricolour/app.py", line 258, in main
    _main(args)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/tricolour-0.1.7-py3.7.egg/tricolour/apps/tricolour/app.py", line 507, in _main
    final_stats)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/threaded.py", line 80, in get
    **kwargs
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/optimization.py", line 1054, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/dask/utils.py", line 29, in apply
    return func(*args, **kwargs)
  File "/data/mjh/anaconda3/lib/python3.7/site-packages/tricolour-0.1.7-py3.7.egg/tricolour/dask_wrappers.py", line 139, in _wrapper
    return np_polarised_intensity(vis, stokes_pol)
TypeError: expected dtype object, got 'numpy.dtype[complex64]'
****ELAPSED 372 TRIC0019

**Comment by IanHeywood** [comment]
I think this is a tricolour / dask-ms / installation issue. Suggest posting the issue here:

https://github.com/ska-sa/tricolour/issues

**Comment by Sinenhlanhla** [comment]
Noted, thanks. I'll post the issue there.

**Comment by IanHeywood** [comment]
https://github.com/ska-sa/tricolour/issues/85
