### ISSUE TITLE
0.42 container issues

### ISSUE THREAD

**Issue by IanHeywood** [IanHeywood/oxkat#56]
fitstool.py:
```
ImportError: liberfa 1.7.2 too old for PyERFA 2.0.0.1. This should only be possible if you are using a system liberfa; try installing using 'pip install pyerfa', with environment variable PYERFA_USE_SYSTEM_LIBERFA unset or 0.
```

shadems:
```
Traceback (most recent call last):
  File "/usr/local/bin/shadems", line 6, in <module>
    from shade_ms import main
  File "/usr/local/lib/python3.9/dist-packages/shade_ms/__init__.py", line 8, in <module>
    from .__main__ import cli, parse_plot_spec, parse_slice_spec  # noqa
  File "/usr/local/lib/python3.9/dist-packages/shade_ms/__main__.py", line 11, in <module>
    __version__ = pkg_resources.require("shadems")[0].version
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (dask 2021.2.0 (/usr/local/lib/python3.9/dist-packages), Requirement.parse('dask==2022.12.0'), {'distributed'})
```

**Comment by IanHeywood** [comment]
Existing containers should be superceded by 0.5 ones soon.
