### ISSUE TITLE
Astropy on Oxkat-0.41.sif container

### ISSUE THREAD

**Issue by IsabellaRammala** [IanHeywood/oxkat#63]
When running submit_info_job.sh, there is an attribute errors related to astropy for all jobs in the script (example below). 
```
Traceback (most recent call last):
  File "/fpra/polmag/02/isabella/mmgps-gc/jwst-mkat/oxkat_reduction/tools/ms_info.py", line 8, in <module>
    from astropy.coordinates import SkyCoord
  File "/usr/lib/python3/dist-packages/astropy/coordinates/__init__.py", line 10, in <module>
    from .angles import *
  File "/usr/lib/python3/dist-packages/astropy/coordinates/angles.py", line 13, in <module>
    from . import angle_utilities as util
  File "/usr/lib/python3/dist-packages/astropy/coordinates/angle_utilities.py", line 30, in <module>
    from astropy import units as u
  File "/usr/lib/python3/dist-packages/astropy/units/__init__.py", line 17, in <module>
    from .quantity import *
  File "/usr/lib/python3/dist-packages/astropy/units/quantity.py", line 28, in <module>
    from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
  File "/usr/lib/python3/dist-packages/astropy/units/quantity_helper/__init__.py", line 10, in <module>
    from . import helpers, function_helpers
  File "/usr/lib/python3/dist-packages/astropy/units/quantity_helper/function_helpers.py", line 119, in <module>
    np.asscalar,
  File "/homes/irammala/.local/lib/python3.9/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'
```

Mostly likely related to astropy.. Failed to import astropy within the singularity container but I can import outside the container. 
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-1010e50adfc0> in <module>()
----> 1 import astropy

ImportError: No module named astropy
```
Looks like it is trying to use the local astropy? I am running python 3.8.10 and Astropy 4.0.1

**Comment by IsabellaRammala** [comment]
When trying `from astropy.coordinates import SkyCoord` the same `AttributeError: module 'numpy' has no attribute 'asscalar'` error is persistent. 


```
AttributeError                            Traceback (most recent call last)
<ipython-input-5-45ece6429792> in <module>
----> 1 import astropy.coordinates

/usr/lib/python3/dist-packages/astropy/coordinates/__init__.py in <module>
      8 
      9 from .errors import *
---> 10 from .angles import *
     11 from .baseframe import *
     12 from .attributes import *

/usr/lib/python3/dist-packages/astropy/coordinates/angles.py in <module>
     11 import numpy as np
     12 
---> 13 from . import angle_utilities as util
     14 from astropy import units as u
     15 from astropy.utils import isiterable

/usr/lib/python3/dist-packages/astropy/coordinates/angle_utilities.py in <module>
     28                      IllegalSecondWarning, IllegalSecondError)
     29 from astropy.utils import format_exception
---> 30 from astropy import units as u
     31 
     32 TAB_HEADER = """# -*- coding: utf-8 -*-

/usr/lib/python3/dist-packages/astropy/units/__init__.py in <module>
     15 # where most time is spent (e.g., using python -X importtime).
     16 from .core import *
---> 17 from .quantity import *
     18 
     19 from . import si

/usr/lib/python3/dist-packages/astropy/units/quantity.py in <module>
     26 from astropy.utils.data_info import ParentDtypeInfo
     27 from astropy import config as _config
---> 28 from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
     29                               check_output)
     30 from .quantity_helper.function_helpers import (

/usr/lib/python3/dist-packages/astropy/units/quantity_helper/__init__.py in <module>
      8 # By importing helpers, all the unit conversion functions needed for
      9 # numpy ufuncs and functions are defined.
---> 10 from . import helpers, function_helpers
     11 # For scipy.special and erfa, importing the helper modules ensures
     12 # the definitions are added as modules to UFUNC_HELPERS, to be loaded

/usr/lib/python3/dist-packages/astropy/units/quantity_helper/function_helpers.py in <module>
    117 IGNORED_FUNCTIONS = {
    118     # Deprecated
--> 119     np.asscalar,
    120     # I/O - useless for Quantity, since no way to store the unit.
    121     np.save, np.savez, np.savetxt, np.savez_compressed,

~/.local/lib/python3.9/site-packages/numpy/__init__.py in __getattr__(attr)
    318             return Tester
    319 
--> 320         raise AttributeError("module {!r} has no attribute "
    321                              "{!r}".format(__name__, attr))
    322 

AttributeError: module 'numpy' has no attribute 'asscalar'
```

**Comment by IanHeywood** [comment]
And this is on a local Bonn machine? If so, I really have no idea, sorry. I'm guessing it's a configuration issue (singularity or otherwise) on the local machine. Maybe ask your local IT people. It seems to run fine for me.

```
ianh@ndidi:~$ singularity shell --bind $PWD ~/containers/oxkat-0.41.sif
Singularity> ipython3
from astroPython 3.9.2 (default, Feb 28 2021, 17:03:44)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from astropy.coordinates import SkyCoord

In [2]:
```

**Comment by IanHeywood** [comment]
You're definitely explicitly using `python3` or `ipython3`? You have to force this when using the oxkat container because it has CASA installed, which defaults everything to python2. Although when I try the problematic import instruction in python2 I still don't get your error...

```
Singularity> ipython
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Python 2.7.12 (default, Apr  4 2017, 16:53:53)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from astropy.coordinates import SkyCoord
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a44fc1d186bf> in <module>()
----> 1 from astropy.coordinates import SkyCoord

ImportError: No module named astropy.coordinates
```

**Comment by IsabellaRammala** [comment]
Thanks. Could be the machine config here. Will have to pass the issue to IT.

**Comment by IanHeywood** [comment]
Thanks @IsabellaRammala and good luck, please reopen if you find something with oxkat is broken.
